name: Deploy ARM Template

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/main.yml"
      - "assets/demo-3-tooling/azuredeploy.json"
      - "assets/demo-3-tooling/3a-cosmos-db.json"
      - "assets/demo-3-tooling/3b-cosmos-db-connection.json"
      - "assets/demo-3-tooling/3c-logic-app.json"

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Test ARM Templates
      id: pathtest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ./assets/demo-3-tooling

    - name: Test results
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"
      
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: github-action-arm-rg
        template: ./assets/demo-3-tooling/azuredeploy.json
        parameters: location=westeurope